version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY="9d#y46+z9*iwrwnpjs*(ynv8=c2oub1tt!(+syt6ga6u#esw1e"
      - DATABASE_URL=postgresql://django:supersecretsquirrel@db:5433/sentiment_reviews
      - ENSIGN_CLIENT_ID
      - ENSIGN_CLIENT_SECRET
      - ENSIGN_INSTANCES_TOPIC
      - ENSIGN_INFERENCES_TOPIC
    depends_on:
      - db
    profiles:
      - all
      - app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sentiment_reviews
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=supersecretsquirrel
    expose:
      - "5433"
    ports:
      - "5433:5433"
    profiles:
      - all
      - db
    command: -p 5433

  predict:
    build:
      context: .
    environment:
      - ENSIGN_CLIENT_ID
      - ENSIGN_CLIENT_SECRET
      - ENSIGN_INSTANCES_TOPIC
      - ENSIGN_INFERENCES_TOPIC
    depends_on:
      - db
      - app
    profiles:
      - all
      - ensign
    command: >
      sh -c "python sentiment.py predict"

  sink:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://django:supersecretsquirrel@db:5433/sentiment_reviews
      - ENSIGN_CLIENT_ID
      - ENSIGN_CLIENT_SECRET
      - ENSIGN_INSTANCES_TOPIC
      - ENSIGN_INFERENCES_TOPIC
    depends_on:
      - db
      - app
    profiles:
      - all
      - ensign
    command: >
      sh -c "python sentiment.py sink"

volumes:
  pgdata: