# Generated by Django 4.2.5 on 2023-09-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The text content of the review to classify', max_length=300)),
                ('polarity', models.CharField(choices=[('UNK', 'Unknown'), ('NEG', 'Negative'), ('NEU', 'Neutral'), ('POS', 'Positive')], default='UNK', help_text='The model inferenced polarity of the review', max_length=3)),
                ('confidence', models.FloatField(default=0.0, help_text='The confidence of the model at inference time')),
                ('features', models.JSONField(blank=True, default=None, help_text='The most informative features for the instance from the model', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'db_table': 'reviews',
                'ordering': ('-created',),
            },
        ),
    ]
